import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create an SVG chart showing all numeric information in metrics.json."
    )
    parser.add_argument(
        "--metrics_json",
        default="LLM_TEST/output/bigvul_cwe119_1_1/metrics.json",
        help="Path to metrics.json generated by recompute_metrics.py",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output SVG path. Defaults to metrics_json directory / reviewed_subset_metrics.svg",
    )
    return parser.parse_args()


def fmt_pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def fmt_num(value: float) -> str:
    if isinstance(value, int) or float(value).is_integer():
        return str(int(value))
    return f"{value:.4f}"


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def svg_rect(x: float, y: float, w: float, h: float, fill: str, rx: int = 0, stroke: str = "none") -> str:
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" '
        f'fill="{fill}" stroke="{stroke}"/>'
    )


def svg_text(
    x: float,
    y: float,
    text: str,
    size: int = 16,
    fill: str = "#16324f",
    weight: str = "400",
    anchor: str = "start",
) -> str:
    return (
        f'<text x="{x}" y="{y}" font-family="Arial, Helvetica, sans-serif" font-size="{size}" '
        f'font-weight="{weight}" fill="{fill}" text-anchor="{anchor}">{esc(text)}</text>'
    )


def draw_metric_chart(parts: list[str], x: int, y: int, width: int, title: str, before: dict, after: dict) -> int:
    ink = "#17324d"
    muted = "#5f6f82"
    grid = "#d8d2c2"
    before_color = "#d1495b"
    after_color = "#2f6b5f"

    chart_h = 220
    bar_w = 28
    inner_gap = 16
    group_gap = 34
    labels = ["accuracy", "precision", "recall", "f1", "fpr"]
    shown = ["Accuracy", "Precision", "Recall", "F1", "FPR"]

    parts.append(svg_rect(x, y, width, 320, "#fffdf7", rx=20))
    parts.append(svg_text(x + 24, y + 34, title, size=22, weight="700", fill=ink))

    base_y = y + 250
    chart_x = x + 28
    chart_w = width - 56

    for i in range(6):
        gy = base_y - i * (chart_h / 5)
        parts.append(f'<line x1="{chart_x}" y1="{gy}" x2="{chart_x + chart_w}" y2="{gy}" stroke="{grid}" stroke-width="1"/>')

    parts.append(f'<line x1="{chart_x}" y1="{base_y}" x2="{chart_x + chart_w}" y2="{base_y}" stroke="{ink}" stroke-width="2"/>')

    start_x = chart_x + 34
    group_w = bar_w * 2 + inner_gap

    for idx, key in enumerate(labels):
        gx = start_x + idx * (group_w + group_gap)
        before_val = float(before[key])
        after_val = float(after[key])
        before_h = chart_h * before_val
        after_h = chart_h * after_val
        by = base_y - before_h
        ay = base_y - after_h

        parts.append(svg_rect(gx, by, bar_w, before_h, before_color, rx=8))
        parts.append(svg_rect(gx + bar_w + inner_gap, ay, bar_w, after_h, after_color, rx=8))
        parts.append(svg_text(gx + bar_w / 2, by - 8, fmt_pct(before_val), size=11, fill=ink, weight="700", anchor="middle"))
        parts.append(svg_text(gx + bar_w + inner_gap + bar_w / 2, ay - 8, fmt_pct(after_val), size=11, fill=ink, weight="700", anchor="middle"))
        parts.append(svg_text(gx + group_w / 2, base_y + 30, shown[idx], size=12, fill=ink, weight="600", anchor="middle"))

    legend_y = y + 292
    parts.append(svg_rect(x + 24, legend_y - 12, 16, 16, before_color, rx=4))
    parts.append(svg_text(x + 50, legend_y + 1, "Before", size=13, fill=muted))
    parts.append(svg_rect(x + 120, legend_y - 12, 16, 16, after_color, rx=4))
    parts.append(svg_text(x + 146, legend_y + 1, "After", size=13, fill=muted))
    return y + 340


def draw_count_chart(parts: list[str], x: int, y: int, width: int, title: str, before: dict, after: dict) -> int:
    ink = "#17324d"
    before_color = "#d1495b"
    after_color = "#2f6b5f"
    grid = "#d8d2c2"

    labels = ["tp", "tn", "fp", "fn", "total"]
    shown = ["TP", "TN", "FP", "FN", "Total"]
    values = [before[k] for k in labels] + [after[k] for k in labels]
    max_val = max(values) or 1
    chart_h = 220
    bar_w = 32
    inner_gap = 18
    group_gap = 42

    parts.append(svg_rect(x, y, width, 320, "#fffdf7", rx=20))
    parts.append(svg_text(x + 24, y + 34, title, size=22, weight="700", fill=ink))

    base_y = y + 250
    chart_x = x + 28
    chart_w = width - 56

    for i in range(6):
        gy = base_y - i * (chart_h / 5)
        parts.append(f'<line x1="{chart_x}" y1="{gy}" x2="{chart_x + chart_w}" y2="{gy}" stroke="{grid}" stroke-width="1"/>')

    parts.append(f'<line x1="{chart_x}" y1="{base_y}" x2="{chart_x + chart_w}" y2="{base_y}" stroke="#17324d" stroke-width="2"/>')

    start_x = chart_x + 26
    group_w = bar_w * 2 + inner_gap
    for idx, key in enumerate(labels):
        gx = start_x + idx * (group_w + group_gap)
        before_val = int(before[key])
        after_val = int(after[key])
        before_h = chart_h * before_val / max_val
        after_h = chart_h * after_val / max_val
        by = base_y - before_h
        ay = base_y - after_h

        parts.append(svg_rect(gx, by, bar_w, before_h, before_color, rx=8))
        parts.append(svg_rect(gx + bar_w + inner_gap, ay, bar_w, after_h, after_color, rx=8))
        parts.append(svg_text(gx + bar_w / 2, by - 8, str(before_val), size=11, fill=ink, weight="700", anchor="middle"))
        parts.append(svg_text(gx + bar_w + inner_gap + bar_w / 2, ay - 8, str(after_val), size=11, fill=ink, weight="700", anchor="middle"))
        parts.append(svg_text(gx + group_w / 2, base_y + 30, shown[idx], size=12, fill=ink, weight="600", anchor="middle"))

    legend_y = y + 292
    parts.append(svg_rect(x + 24, legend_y - 12, 16, 16, before_color, rx=4))
    parts.append(svg_text(x + 50, legend_y + 1, "Before", size=13, fill="#5f6f82"))
    parts.append(svg_rect(x + 120, legend_y - 12, 16, 16, after_color, rx=4))
    parts.append(svg_text(x + 146, legend_y + 1, "After", size=13, fill="#5f6f82"))
    return y + 340


def draw_info_block(parts: list[str], x: int, y: int, width: int, title: str, rows: list[tuple[str, str]]) -> int:
    ink = "#17324d"
    muted = "#5f6f82"
    row_h = 28
    height = 58 + len(rows) * row_h
    parts.append(svg_rect(x, y, width, height, "#fffdf7", rx=20))
    parts.append(svg_text(x + 24, y + 34, title, size=22, weight="700", fill=ink))
    cy = y + 68
    for label, value in rows:
        parts.append(svg_text(x + 24, cy, label, size=14, fill=muted, weight="600"))
        parts.append(svg_text(x + width - 24, cy, value, size=14, fill=ink, weight="700", anchor="end"))
        cy += row_h
    return y + height + 20


def build_svg(metrics: dict) -> str:
    width = 1320
    height = 2060
    bg = "#f7f4ea"
    panel = "#fefcf6"
    ink = "#17324d"
    muted = "#5f6f82"

    original_all = metrics["original_metrics"]
    final_all = metrics["final_metrics"]
    original_subset = metrics["reviewed_subset_original_metrics"]
    final_subset = metrics["reviewed_subset_final_metrics"]
    positive = metrics["positive_case_summary"]
    scope = metrics["metrics_scope"]

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        svg_rect(0, 0, width, height, bg),
        svg_rect(34, 24, width - 68, height - 48, panel, rx=28),
        svg_text(72, 78, "Metrics Overview", size=30, weight="700", fill=ink),
        svg_text(72, 110, "All numeric information from metrics.json", size=16, fill=muted),
    ]

    y = 150
    y = draw_info_block(
        parts,
        60,
        y,
        1200,
        "Files And Scope",
        [
            ("results_csv", metrics["results_csv"]),
            ("llm_predictions_csv", metrics["llm_predictions_csv"]),
            ("positive_case_details_csv", metrics["positive_case_details_csv"]),
            ("llm_override_count", fmt_num(metrics["llm_override_count"])),
            ("llm_missing_count", fmt_num(metrics["llm_missing_count"])),
            ("original_metrics scope", scope["original_metrics"]),
            ("final_metrics scope", scope["final_metrics"]),
            ("reviewed_subset_original_metrics scope", scope["reviewed_subset_original_metrics"]),
            ("reviewed_subset_final_metrics scope", scope["reviewed_subset_final_metrics"]),
        ],
    )

    y = draw_metric_chart(parts, 60, y, 1200, "All Test Cases: Metric Comparison", original_all, final_all)
    y = draw_count_chart(parts, 60, y, 1200, "All Test Cases: Confusion Matrix Counts", original_all, final_all)
    y = draw_metric_chart(parts, 60, y, 1200, "Reviewed Subset (OriginalPrediction == 1): Metric Comparison", original_subset, final_subset)
    y = draw_count_chart(parts, 60, y, 1200, "Reviewed Subset (OriginalPrediction == 1): Confusion Matrix Counts", original_subset, final_subset)

    y = draw_info_block(
        parts,
        60,
        y,
        1200,
        "Positive Case Summary",
        [
            ("actual_positive_total", fmt_num(positive["actual_positive_total"])),
            ("actual_positive_reviewed_by_llm", fmt_num(positive["actual_positive_reviewed_by_llm"])),
            ("actual_positive_missed_by_original", fmt_num(positive["actual_positive_missed_by_original"])),
            ("actual_positive_kept_by_llm", fmt_num(positive["actual_positive_kept_by_llm"])),
            ("actual_positive_rejected_by_llm", fmt_num(positive["actual_positive_rejected_by_llm"])),
            ("original_recall_on_actual_positives", fmt_pct(positive["original_recall_on_actual_positives"])),
            ("final_recall_on_actual_positives", fmt_pct(positive["final_recall_on_actual_positives"])),
            ("llm_keep_rate_within_reviewed_actual_positives", fmt_pct(positive["llm_keep_rate_within_reviewed_actual_positives"])),
            ("llm_reject_rate_within_reviewed_actual_positives", fmt_pct(positive["llm_reject_rate_within_reviewed_actual_positives"])),
        ],
    )

    parts.append(svg_text(72, height - 40, "Generated from metrics.json by plot_reviewed_subset_metrics.py", size=12, fill="#7c8796"))
    parts.append("</svg>")
    return "\n".join(parts)


def main() -> None:
    args = parse_args()
    metrics_path = Path(args.metrics_json).resolve()
    output_path = (
        Path(args.output).resolve()
        if args.output
        else metrics_path.parent / "reviewed_subset_metrics.svg"
    )
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    svg = build_svg(metrics)
    output_path.write_text(svg, encoding="utf-8")
    print(output_path)


if __name__ == "__main__":
    main()
